vp:
  image: hyperledger/fabric-peer
  ports:
    - "5000:5000"
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://localhost:2375
    - CORE_LOGGING_LEVEL=DEBUG
  command: sh -c "sleep 5; peer node start"
membersrvc:
   image: hyperledger/fabric-membersrvc
   command: membersrvc
   